# Generated by Django 6.0.5 on 2026-08-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MNSEA KINGS CORPORATION', max_length=100)),
                ('tagline', models.CharField(default='Fresh Seafood. Quality Meat. Fast Delivery.', max_length=200)),
                ('banner_message', models.CharField(blank=True, default='Free delivery on orders above ₹999 | Fresh cut & delivered same day', help_text='Scrolling/top banner message shown on every page.', max_length=250)),
                ('contact_phone', models.CharField(default='+91 90000 00000', max_length=20)),
                ('contact_whatsapp', models.CharField(blank=True, default='+91 90000 00000', max_length=20)),
                ('contact_email', models.EmailField(default='orders@mnseakings.in', max_length=254)),
                ('upi_id', models.CharField(blank=True, default='mnseakings@upi', max_length=100)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=49.0, max_digits=8)),
                ('free_delivery_above', models.DecimalField(decimal_places=2, default=999.0, max_digits=8)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=299.0, max_digits=8)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('facebook_url', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
