# Generated by Django 6.0.5 on 2026-08-27 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('icon_emoji', models.CharField(blank=True, default='🐟', help_text='Small emoji shown next to the category, e.g. 🐟 🦐 🍗 🐐', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('unit', models.CharField(choices=[('kg', 'per kg'), ('500g', 'per 500g'), ('250g', 'per 250g'), ('piece', 'per piece'), ('dozen', 'per dozen'), ('pack', 'per pack')], default='kg', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text="Today's selling price", max_digits=8)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, help_text='Optional strike-through price to show a discount', max_digits=8, null=True)),
                ('price_updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck when out of stock')),
                ('is_featured', models.BooleanField(default=False, help_text="Show on homepage 'Today's Catch' section")),
                ('is_bestseller', models.BooleanField(default=False)),
                ('cut_info', models.CharField(blank=True, help_text="e.g. 'Cleaned & Curry Cut', 'Whole, Descaled', 'Boneless'", max_length=150)),
                ('origin', models.CharField(blank=True, help_text="e.g. 'Kakinada Coast', 'Farm Fresh'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
