# Generated by Django 6.1 on 2026-08-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon_emoji',
            field=models.CharField(blank=True, default='🐟', help_text='Product icon shown when no product photo is uploaded.', max_length=10),
        ),
    ]
