# Generated by Django 6.1 on 2026-08-28 06:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Monthly Stock Book',
                'verbose_name_plural': 'Monthly Stock Books',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_stock_month')],
            },
        ),
        migrations.CreateModel(
            name='StockDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('stock_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='inventory.stockmonth')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='StockLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('received_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('sold_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('returns_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('wastage_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=250)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockday')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lines', to='catalog.product')),
            ],
            options={
                'ordering': ['product__category__display_order', 'product__name'],
                'constraints': [models.UniqueConstraint(fields=('day', 'product'), name='unique_stock_line_product_day')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockday',
            constraint=models.UniqueConstraint(fields=('stock_month', 'date'), name='unique_stock_day'),
        ),
    ]
