# Generated by Django 6.1 on 2026-08-27 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_paid_at_order_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('razorpay_order_created', 'Razorpay Order Created'), ('callback_verified', 'Payment Verified (Browser Callback)'), ('callback_signature_invalid', 'Signature Verification Failed (Browser Callback)'), ('webhook_captured', 'Webhook: Payment Captured'), ('webhook_failed', 'Webhook: Payment Failed'), ('webhook_signature_invalid', 'Webhook Signature Invalid')], max_length=40)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
